/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colormixer;

import java.awt.Color;

/**
 *
 * @author tangminhtin
 */
public class frmColorMixer extends javax.swing.JFrame {

    /**
     * Creates new form frmColorMixer
     */
    public frmColorMixer() {
        initComponents();
        
        // Set center window
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();
        sdBlue = new javax.swing.JSlider();
        lblBlue = new javax.swing.JLabel();
        sdGreen = new javax.swing.JSlider();
        lblGreen = new javax.swing.JLabel();
        sdRed = new javax.swing.JSlider();
        lblRed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Color Mixing");

        lblText.setBackground(new java.awt.Color(255, 255, 255));
        lblText.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setText("This is demo text!");
        lblText.setOpaque(true);

        sdBlue.setBackground(new java.awt.Color(204, 255, 0));
        sdBlue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sdBlue.setForeground(new java.awt.Color(0, 0, 255));
        sdBlue.setMajorTickSpacing(50);
        sdBlue.setMaximum(255);
        sdBlue.setMinorTickSpacing(25);
        sdBlue.setOrientation(javax.swing.JSlider.VERTICAL);
        sdBlue.setPaintLabels(true);
        sdBlue.setPaintTicks(true);
        sdBlue.setToolTipText("");
        sdBlue.setValue(0);
        sdBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdBlueStateChanged(evt);
            }
        });

        lblBlue.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblBlue.setForeground(new java.awt.Color(0, 0, 255));
        lblBlue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBlue.setText("Blue");

        sdGreen.setBackground(new java.awt.Color(204, 255, 0));
        sdGreen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sdGreen.setForeground(new java.awt.Color(0, 255, 0));
        sdGreen.setMajorTickSpacing(50);
        sdGreen.setMaximum(255);
        sdGreen.setMinorTickSpacing(25);
        sdGreen.setOrientation(javax.swing.JSlider.VERTICAL);
        sdGreen.setPaintLabels(true);
        sdGreen.setPaintTicks(true);
        sdGreen.setToolTipText("");
        sdGreen.setValue(0);
        sdGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdGreenStateChanged(evt);
            }
        });

        lblGreen.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblGreen.setForeground(new java.awt.Color(0, 255, 0));
        lblGreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGreen.setText("Green");

        sdRed.setBackground(new java.awt.Color(204, 255, 0));
        sdRed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sdRed.setForeground(new java.awt.Color(255, 0, 0));
        sdRed.setMajorTickSpacing(50);
        sdRed.setMaximum(255);
        sdRed.setMinorTickSpacing(25);
        sdRed.setOrientation(javax.swing.JSlider.VERTICAL);
        sdRed.setPaintLabels(true);
        sdRed.setPaintTicks(true);
        sdRed.setToolTipText("");
        sdRed.setValue(0);
        sdRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdRedStateChanged(evt);
            }
        });

        lblRed.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblRed.setForeground(new java.awt.Color(255, 0, 0));
        lblRed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRed.setText("Red");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sdRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblGreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sdGreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblBlue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sdBlue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sdGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGreen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sdRed, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRed))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sdBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBlue)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeColor() {
        Color textColor = new Color(sdRed.getValue(), sdGreen.getValue(), sdBlue.getValue());
        Color backgroundColor = new Color(255 - sdRed.getValue(), 255 - sdGreen.getValue(), 255 - sdBlue.getValue());
        
        lblText.setForeground(textColor);
        lblText.setBackground(backgroundColor);
    }
    
    private void sdRedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdRedStateChanged
        changeColor();
    }//GEN-LAST:event_sdRedStateChanged

    private void sdGreenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdGreenStateChanged
        changeColor();
    }//GEN-LAST:event_sdGreenStateChanged

    private void sdBlueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdBlueStateChanged
        changeColor();
    }//GEN-LAST:event_sdBlueStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmColorMixer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmColorMixer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmColorMixer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmColorMixer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmColorMixer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBlue;
    private javax.swing.JLabel lblGreen;
    private javax.swing.JLabel lblRed;
    private javax.swing.JLabel lblText;
    private javax.swing.JSlider sdBlue;
    private javax.swing.JSlider sdGreen;
    private javax.swing.JSlider sdRed;
    // End of variables declaration//GEN-END:variables
}
