/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.mydictionary;

import Server.Models.WordModel;
import Server.MyServer.I_WordModel;
import Server.ObjectInfos.Word;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tangminhtin
 */
public class TestCreator extends javax.swing.JFrame {

    EnEnDictionary parent;  // Declare parent
//    WordModel wm;           // Declare wm
    ArrayList<Word> theTest;    // Declare theTest
    ArrayList<String> userInput;    // Declare userInput
    Testing frmTesting = null;  // Declare frmTesting
    
    
        I_WordModel wm;


    /**
     * Creates new form TestCreator
     *
     * @param parent parent
     * @param wm word model
     * @param theTest theTest
     * @param userInput userInput
     */
    public TestCreator(EnEnDictionary parent, I_WordModel wm, ArrayList<Word> theTest, ArrayList<String> userInput) {
        initComponents();
        this.setLocationRelativeTo(null);   // Set center frame
        // Set logo frame
        this.setIconImage(getToolkit().getDefaultToolkit().getImage(getClass().getResource("/Client/img/logo.png")));

        this.parent = parent;   // Initialize parent
        this.wm = wm;           // Initialize wm
        this.theTest = theTest; // Initialize theTest
        this.userInput = userInput; // Initialize userInput
    }

    /**
     * Refresh data
     * @throws java.rmi.RemoteException
     */
    public void refresh() throws RemoteException {
        cmbNum.removeAllItems();
        for (int i = 0; i < wm.getSize(); i++) {
            cmbNum.addItem((i + 1) + "");   // Set combox
        }
        chkRandom.setSelected(true); // Set check box is selected
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        lblRandom = new javax.swing.JLabel();
        cmbNum = new javax.swing.JComboBox<>();
        chkRandom = new javax.swing.JCheckBox();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Test Setup");
        setName("frmSetup"); // NOI18N

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("TEST SETUP");

        lblNum.setText("Number of words");

        lblRandom.setText("Randomize?");

        cmbNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chkRandom.setText("Yes");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRandom)
                            .addComponent(lblNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbNum, 0, 183, Short.MAX_VALUE)
                            .addComponent(chkRandom)
                            .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum)
                    .addComponent(cmbNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRandom)
                    .addComponent(chkRandom))
                .addGap(10, 10, 10)
                .addComponent(btnOK)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Create Testing
     *
     * @param evt click
     */
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        try {
            int n = Integer.parseInt(String.valueOf(cmbNum.getSelectedItem())); // Get number of question
            boolean isShuffe = chkRandom.isSelected();  // Check random or not
            theTest = wm.generateTest(n, isShuffe);     // Create test
            this.setVisible(false); // Hide current frame
            
            if (frmTesting == null) {   // If frmTesting is null, then create new frmTesting
                frmTesting = new Testing(parent, wm, theTest, userInput);
            }
            frmTesting.refresh(); // Reload data
            frmTesting.setVisible(true); // Show frame
        } catch (RemoteException ex) {
            Logger.getLogger(TestCreator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TestCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TestCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TestCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TestCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TestCreator().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JCheckBox chkRandom;
    private javax.swing.JComboBox<String> cmbNum;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblRandom;
    // End of variables declaration//GEN-END:variables
}
