/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personalinfo;

/**
 *
 * @author tangminhtin
 */
public class frmChangeBirthday extends javax.swing.JFrame {

    /**
     * Creates new form frmChangeBirthday
     */
    public frmChangeBirthday() {
        initComponents();
    }
    
    /**
     * Gets birthday
     * @return 
     */
    public String getBirthday() {
        return ftfBirthday.getText();
    }
    
    /**
     * Sets birthday
     * @param text 
     */
    public void setBirthday(String text) {
        ftfBirthday.setText(text);
    }

            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTChangeBirthday = new javax.swing.JLabel();
        ftfBirthday = new javax.swing.JFormattedTextField();
        lblFormat = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change name");

        lblTChangeBirthday.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTChangeBirthday.setText("Please enter your birthday:");

        ftfBirthday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        ftfBirthday.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        lblFormat.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblFormat.setText("(dd/MM/yyyy)");

        btnOK.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTChangeBirthday)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ftfBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFormat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTChangeBirthday)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOK)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Click to confirm value and close 
     * @param evt 
     */
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // Create new personalInfo
        frmPersonalInfo personalInfo = new frmPersonalInfo();
        
        // Set birthday for ftfBirthday
        personalInfo.setBirthday(ftfBirthday.getText());
        
        // Hide current window and show window of personalInfo
        this.setVisible(false);
        personalInfo.setVisible(true);
    }//GEN-LAST:event_btnOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JFormattedTextField ftfBirthday;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lblTChangeBirthday;
    // End of variables declaration//GEN-END:variables
}
